<Project>

	<PropertyGroup>
		<Version>0.5.1</Version>
		<Authors>VeyDlin</Authors>
		<RepositoryUrl>https://github.com/VeyDlin/IDEncoder</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

</Project>
